<<<<<<< HEAD
# Generated by Django 3.1 on 2020-09-22 02:54
=======
# Generated by Django 3.1 on 2020-09-21 23:05
>>>>>>> 7d575f995544f4299c9bd6c32e225599840b9c2e

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
=======
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=170)),
                ('enlace', models.CharField(max_length=500)),
>>>>>>> 7d575f995544f4299c9bd6c32e225599840b9c2e
            ],
        ),
    ]
