# Generated by Django 3.1 on 2020-09-11 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('nro_escuela', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('establecimiento', models.ManyToManyField(to='Establecimientos.Establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Orientacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('oferta', models.ManyToManyField(to='Establecimientos.Oferta')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Establecimientos.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('altura', models.IntegerField()),
                ('departamento', models.CharField(max_length=50)),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Establecimientos.localizacion')),
            ],
        ),
    ]
