# Generated by Django 3.1 on 2020-09-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='id_localizacion',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='id_localizacion',
            field=models.ManyToManyField(to='Establecimientos.Localizacion'),
        ),
    ]
