# Generated by Django 3.1 on 2020-09-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='nro_escuela',
            field=models.IntegerField(null=True),
        ),
    ]
